### ISSUE TITLE
qt error

### ISSUE THREAD

**Issue by gildas04** [Tiryoh/docker-ros2#27]
Hi, 
i got this output, when i try to run turtlesim.

root@505e68ca4bea:~# ros2 run turtlesim turtlesim_node
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

can you help me?

**Comment by Tiryoh** [comment]
Have you configured X11 forwarding?

https://github.com/osrf/rocker makes easier to configure X11 forwarding.

example: https://github.com/Tiryoh/rocker-ros-configs/blob/main/launch.sh

**Comment by gildas04** [comment]
Thanks Tiryoh, it works now.
